# general
seed: 1
device: 'cuda'
output_path: 'PNP-results/tshirtman-milkyway'

# data
image_path: 'assets/Samples/tshirtman-milkyway.png'
latents_path: 'latents_forward'

# diffusion
sd_version: '2.1'
guidance_scale: 7.5
n_timesteps: 50
prompt: a man walks in the filed, milky way 
negative_prompt: ugly

# pnp injection thresholds, ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
